definitions:
  models.FileNode:
    properties:
      children:
        items:
          $ref: '#/definitions/models.FileNode'
        type: array
      is_dir:
        type: boolean
      name:
        type: string
      path:
        type: string
    type: object
  payloads.RequestData:
    properties:
      filePath:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/content:
    get:
      description: Get list of files and directories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.FileNode'
            type: array
      summary: Get directory contents
      tags:
      - content
  /api/markdown:
    post:
      consumes:
      - application/json
      description: 根据提供的文件路径获取Markdown文件的内容
      parameters:
      - description: 请求数据
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payloads.RequestData'
      produces:
      - application/json
      responses:
        "200":
          description: Markdown file content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: 获取Markdown内容
      tags:
      - markdown
swagger: "2.0"
